apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce

type: Opaque

stringData:
  DATABASE_URL: ""
  JWT_SECRET: ""
  JWT_REFRESH_SECRET: ""
  COOKIE_SECRET: ""

  RAZORPAY_KEY_ID: ""
  RAZORPAY_KEY_SECRET: ""

  STRIPE_SECRET_KEY: ""

  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""