FROM oven/bun:1.2.21

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY package.json bun.lock ./

RUN bun install --frozen-lockfile

COPY . .

RUN bunx prisma generate

ENV NODE_ENV=production

CMD ["bun","run","src/worker.ts"]
