import { useEffect, useState } from "react";
import { Pencil, Plus, Trash2, X } from "lucide-react";
import { adminApi, type Category } from "@/lib/admin-api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PageHeader, Loading, ErrorState, Empty, Badge } from "./common";

function CategoryForm({ initial, onClose, onSaved }: { initial?: Category; onClose:()=>void; onSaved:()=>void }) {
 const [name,setName]=useState(initial?.name??""); const [active,setActive]=useState(initial?.isActive??true); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(name.trim().length<2){setError("Category name must be at least 2 characters.");return}try{setBusy(true);setError("");if(initial)await adminApi.updateCategory(initial.id,{name:name.trim(),isActive:active});else await adminApi.createCategory({name:name.trim(),isActive:active});onSaved()}catch(e){setError(e instanceof Error?e.message:"Unable to save category.")}finally{setBusy(false)}};
 return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form onSubmit={save} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-lg font-semibold">{initial?"Edit category":"Create category"}</h2><p className="text-sm text-muted-foreground">The backend generates the slug.</p></div><button type="button" onClick={onClose}><X/></button></div>{error&&<div className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="mt-5"><Label>Name</Label><Input className="mt-2" value={name} onChange={e=>setName(e.target.value)} required maxLength={100}/></div><label className="mt-5 flex items-center gap-2 text-sm"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Active category</label><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button disabled={busy}>{busy?"Saving…":"Save"}</Button></div></form></div>;
}

export default function CategoriesPage(){
 const [categories,setCategories]=useState<Category[]>([]);const [search,setSearch]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[editing,setEditing]=useState<Category|"new"|null>(null);const[notice,setNotice]=useState("");
 const load=async()=>{try{setLoading(true);setError("");setCategories(await adminApi.categories(search.trim()||undefined))}catch(e){setError(e instanceof Error?e.message:"Unable to load categories.")}finally{setLoading(false)}};useEffect(()=>{void load()},[search]);
 const remove=async(c:Category)=>{if(!window.confirm(`Delete "${c.name}"? Products referencing it may prevent deletion.`))return;try{await adminApi.deleteCategory(c.id);setNotice("Category deleted.");void load()}catch(e){setError(e instanceof Error?e.message:"Unable to delete category.")}};
 return <div><PageHeader title="Categories" description="Manage catalog categories." action={<Button onClick={()=>setEditing("new")}><Plus/>New category</Button>}/>{notice&&<div className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}{error&&<div className="mb-4"><ErrorState message={error} retry={load}/></div>}<div className="mb-4 max-w-md"><Input placeholder="Search categories…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{loading?<Loading/>:categories.length===0?<Empty title="No categories found"/>:<div className="overflow-hidden rounded-xl border bg-card"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr className="text-left text-muted-foreground"><th className="p-3">Name</th><th className="p-3">Slug</th><th className="p-3">Products</th><th className="p-3">Status</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{categories.map(c=><tr key={c.id} className="border-t"><td className="p-3 font-medium">{c.name}</td><td className="p-3 text-muted-foreground">{c.slug}</td><td className="p-3">{c.products?.length??"—"}</td><td className="p-3"><Badge tone={c.isActive?"green":"red"}>{c.isActive?"ACTIVE":"INACTIVE"}</Badge></td><td className="p-3"><div className="flex justify-end gap-2"><Button size="sm" variant="outline" onClick={()=>setEditing(c)}><Pencil/></Button><Button size="sm" variant="destructive" onClick={()=>void remove(c)}><Trash2/></Button></div></td></tr>)}</tbody></table></div></div>}{editing&&<CategoryForm initial={editing==="new"?undefined:editing} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);setNotice(editing==="new"?"Category created.":"Category updated.");void load()}}/>}</div>;
}
