import { useEffect, useState } from "react";
import { Pencil, Plus, Trash2, X } from "lucide-react";
import { adminApi, type Coupon } from "@/lib/admin-api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PageHeader, Loading, ErrorState, Empty, Badge, formatMoney, formatDate } from "./common";

type FormState = { code: string; description: string; type: "PERCENTAGE" | "FIXED"; value: number; minimumOrderAmount: number | ""; maximumDiscount: number | ""; usageLimit: number | ""; startsAt: string; expiresAt: string; isActive: boolean };

function CouponForm({ initial, onClose, onSaved }: { initial?: Coupon; onClose: () => void; onSaved: () => void }) {
  const [f, setF] = useState<FormState>({ code: initial?.code ?? "", description: initial?.description ?? "", type: initial?.type ?? "PERCENTAGE", value: Number(initial?.value ?? 0), minimumOrderAmount: initial?.minimumOrderAmount == null ? "" : Number(initial.minimumOrderAmount), maximumDiscount: initial?.maximumDiscount == null ? "" : Number(initial.maximumDiscount), usageLimit: initial?.usageLimit ?? "", startsAt: initial?.startsAt ? initial.startsAt.slice(0, 16) : "", expiresAt: initial?.expiresAt ? initial.expiresAt.slice(0, 16) : "", isActive: initial?.isActive ?? true });
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const save = async (e: React.FormEvent) => { e.preventDefault(); try { setBusy(true); setError(""); const input = { ...f, code: f.code.trim().toUpperCase(), minimumOrderAmount: f.minimumOrderAmount === "" ? undefined : Number(f.minimumOrderAmount), maximumDiscount: f.maximumDiscount === "" ? undefined : Number(f.maximumDiscount), usageLimit: f.usageLimit === "" ? undefined : Number(f.usageLimit), startsAt: f.startsAt ? new Date(f.startsAt).toISOString() : undefined, expiresAt: f.expiresAt ? new Date(f.expiresAt).toISOString() : undefined }; if (initial) await adminApi.updateCoupon(initial.id, input); else await adminApi.createCoupon(input); onSaved(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save coupon."); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-4"><form onSubmit={save} className="mx-auto my-8 max-w-2xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-lg font-semibold">{initial ? "Edit coupon" : "Create coupon"}</h2><p className="text-sm text-muted-foreground">Coupon rules are enforced by the checkout backend.</p></div><button type="button" onClick={onClose}><X /></button></div>{error && <div className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><div><Label>Code</Label><Input className="mt-2" value={f.code} onChange={e => setF({ ...f, code: e.target.value })} required /></div><div><Label>Type</Label><select className="mt-2 h-9 w-full rounded-md border px-3 text-sm" value={f.type} onChange={e => setF({ ...f, type: e.target.value as FormState["type"] })}><option>PERCENTAGE</option><option>FIXED</option></select></div><div><Label>Value</Label><Input className="mt-2" type="number" min="0.01" step="0.01" value={f.value} onChange={e => setF({ ...f, value: Number(e.target.value) })} /></div><div><Label>Minimum order</Label><Input className="mt-2" type="number" min="0" step="0.01" value={f.minimumOrderAmount} onChange={e => setF({ ...f, minimumOrderAmount: e.target.value === "" ? "" : Number(e.target.value) })} /></div><div><Label>Maximum discount</Label><Input className="mt-2" type="number" min="0" step="0.01" value={f.maximumDiscount} onChange={e => setF({ ...f, maximumDiscount: e.target.value === "" ? "" : Number(e.target.value) })} /></div><div><Label>Usage limit</Label><Input className="mt-2" type="number" min="1" step="1" value={f.usageLimit} onChange={e => setF({ ...f, usageLimit: e.target.value === "" ? "" : Number(e.target.value) })} /></div><div><Label>Starts</Label><Input className="mt-2" type="datetime-local" value={f.startsAt} onChange={e => setF({ ...f, startsAt: e.target.value })} /></div><div><Label>Expires</Label><Input className="mt-2" type="datetime-local" value={f.expiresAt} onChange={e => setF({ ...f, expiresAt: e.target.value })} /></div></div>
    <div className="mt-4"><Label>Description</Label><Input className="mt-2" value={f.description} onChange={e => setF({ ...f, description: e.target.value })} /></div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={f.isActive} onChange={e => setF({ ...f, isActive: e.target.checked })} /> Active</label>
    <div className="mt-6 flex justify-end gap-2 border-t pt-5"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button disabled={busy}>{busy ? "Saving…" : "Save coupon"}</Button></div></form></div>;
}

export default function CouponsPage() {
  const [data, setData] = useState<Coupon[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editing, setEditing] = useState<Coupon | "new" | null>(null);
  const load = async () => { try { setLoading(true); setError(""); setData(await adminApi.coupons()); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load coupons."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const remove = async (c: Coupon) => { if (!window.confirm(`Delete coupon ${c.code}?`)) return; try { await adminApi.deleteCoupon(c.id); void load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to delete coupon."); } };
  return <div><PageHeader title="Coupons" description="Manage promotional rules used by checkout." action={<Button onClick={() => setEditing("new")}><Plus />New coupon</Button>} />{error && <div className="mb-4"><ErrorState message={error} retry={load} /></div>}{loading ? <Loading /> : data.length === 0 ? <Empty title="No coupons" description="Create a coupon to make one available at checkout." /> : <div className="overflow-hidden rounded-xl border bg-card"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr className="text-left text-muted-foreground"><th className="p-3">Code</th><th className="p-3">Rule</th><th className="p-3">Usage</th><th className="p-3">Validity</th><th className="p-3">State</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{data.map(c => <tr key={c.id} className="border-t"><td className="p-3 font-semibold">{c.code}<p className="text-xs font-normal text-muted-foreground">{c.description}</p></td><td className="p-3">{c.type === "PERCENTAGE" ? `${c.value}%` : formatMoney(c.value)}</td><td className="p-3">{c.usedCount}{c.usageLimit ? ` / ${c.usageLimit}` : ""}</td><td className="p-3 text-xs">{formatDate(c.startsAt ?? undefined)}<br />{formatDate(c.expiresAt ?? undefined)}</td><td className="p-3"><Badge tone={c.isActive ? "green" : "red"}>{c.isActive ? "ACTIVE" : "INACTIVE"}</Badge></td><td className="p-3"><div className="flex justify-end gap-2"><Button size="sm" variant="outline" onClick={() => setEditing(c)}><Pencil /></Button><Button size="sm" variant="destructive" onClick={() => void remove(c)}><Trash2 /></Button></div></td></tr>)}</tbody></table></div></div>}{editing && <CouponForm initial={editing === "new" ? undefined : editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void load(); }} />}</div>;
}
