import { useEffect, useState } from "react";
import { Search, RotateCcw } from "lucide-react";
import { adminApi, type Payment, type PaymentProvider, type PaymentStatus } from "@/lib/admin-api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeader, Loading, ErrorState, Empty, Badge, formatDate, formatMoney, statusTone } from "./common";

const statuses: PaymentStatus[] = ["PENDING", "PAID", "FAILED", "REFUNDED"];

export default function PaymentsPage() {
  const [data, setData] = useState<Payment[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [provider, setProvider] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const limit = 15;
  const load = async () => { try { setLoading(true); setError(""); const r = await adminApi.payments({ page, limit, search: search.trim() || undefined, status: (status || undefined) as PaymentStatus | undefined, provider: (provider || undefined) as PaymentProvider | undefined }); setData(r.data); setTotal(r.pagination.total); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load payments."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [page, search, status, provider]);
  const refund = async (payment: Payment) => { if (!window.confirm(`Refund ${formatMoney(payment.amount)} for ${payment.order?.orderNumber ?? "this payment"}?`)) return; const reason = window.prompt("Refund reason (optional):") ?? undefined; try { await adminApi.refundPayment(payment.id, reason); void load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to refund payment."); } };
  return <div><PageHeader title="Payments & refunds" description="Review payment records and issue full refunds for eligible paid payments." />{error && <div className="mb-4"><ErrorState message={error} retry={load} /></div>}
    <div className="mb-4 grid gap-3 md:grid-cols-[1fr_180px_160px]"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" placeholder="Search payment, order or customer…" value={search} onChange={e => { setPage(1); setSearch(e.target.value); }} /></div><select className="h-9 rounded-md border px-3 text-sm" value={status} onChange={e => { setPage(1); setStatus(e.target.value); }}><option value="">All statuses</option>{statuses.map(s => <option key={s}>{s}</option>)}</select><select className="h-9 rounded-md border px-3 text-sm" value={provider} onChange={e => { setPage(1); setProvider(e.target.value); }}><option value="">All providers</option><option>RAZORPAY</option><option>STRIPE</option></select></div>
    {loading ? <Loading /> : data.length === 0 ? <Empty title="No payments found" /> : <div className="overflow-hidden rounded-xl border bg-card"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr className="text-left text-muted-foreground"><th className="p-3">Payment</th><th className="p-3">Customer</th><th className="p-3">Order</th><th className="p-3">Amount</th><th className="p-3">Status</th><th className="p-3">Created</th><th className="p-3 text-right">Action</th></tr></thead><tbody>{data.map(p => <tr key={p.id} className="border-t"><td className="p-3"><p className="font-medium">{p.provider}</p><p className="text-xs text-muted-foreground">{p.providerPaymentId ?? p.providerOrderId ?? p.id}</p></td><td className="p-3">{p.user.name}<p className="text-xs text-muted-foreground">{p.user.email}</p></td><td className="p-3">{p.order?.orderNumber ?? "—"}</td><td className="p-3 font-medium">{formatMoney(p.amount)}</td><td className="p-3"><Badge tone={statusTone(p.status)}>{p.status}</Badge></td><td className="p-3">{formatDate(p.createdAt)}</td><td className="p-3 text-right">{p.status === "PAID" && <Button size="sm" variant="outline" onClick={() => void refund(p)}><RotateCcw />Refund</Button>}</td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t p-3 text-sm"><span>Page {page} of {Math.max(1, Math.ceil(total / limit))}</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page <= 1} onClick={() => setPage(p => p - 1)}>Previous</Button><Button size="sm" variant="outline" disabled={page >= Math.ceil(total / limit)} onClick={() => setPage(p => p + 1)}>Next</Button></div></div></div>}
  </div>;
}
