groups:

  - name: backend-alerts

    rules:

      - alert: BackendDown

        expr: up{job="backend-api"} == 0

        for: 30s

        labels:
          severity: critical

        annotations:
          summary: Backend Down
          description: API is unreachable

      - alert: HighCPU

        expr: process_cpu_seconds_total > 0.8

        for: 2m

        labels:
          severity: warning

      - alert: HighMemory

        expr: process_resident_memory_bytes > 700000000

        for: 2m

        labels:
          severity: warning